NecessaryTools/Controllers/Alyaradat Walmasrufat/AlMasrufatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NecessaryTools.Models.Alyaradat_Walmasrufat;

namespace NecessaryTools.Controllers.Alyaradat_Walmasrufat
{
    public class AlMasrufatController : Controller
    {
        // GET: AlMasrufat
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult Save(AlMasrufat alMasrufat)
        //{
            
        //}
    }
    
}

NecessaryTools/Controllers/Alyaradat Walmasrufat/AlYardatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NecessaryTools.Controllers.Alyaradat_Walmasrufat
{
    public class AlYardatController : Controller
    {
        // GET: AlYardat
        public ActionResult Index()
        {
            return View();
        }
    }
}

NecessaryTools/Controllers/MissMatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NecessaryTools.Models;

namespace NecessaryTools.Controllers
{
    public class MissMatchController : Controller
    {
		// GET: MissMatch
		public ActionResult Index()
		{
			return View();
		}

        public ActionResult Find(MissMatch aMissMatch)
        {
            List<MissMatch.Missing> missList = MissMatch.GetMissingItems(aMissMatch);
            if (missList.Count == 0)
                return  Json("All data in list b is cosist in list a.");
            else
            {
                return Json(missList);
            }
        }

        public ActionResult AgeCal(MissMatch.AgeCalculator newAgeCalculator)
        {
            return Json(MissMatch.AgeCalculator.AgeCalculate(newAgeCalculator));
        }
    }
}

NecessaryTools/Controllers/PassMakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NecessaryTools.Models;

namespace NecessaryTools.Controllers
{
    public class PassMakeController : Controller
    {
        // GET: PassMake
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PassGen(string Pass)
        {
            PassMake aPassMake = new PassMake(Pass);
            return Json(aPassMake);
        }
        public ActionResult GtrPass(string Pass)
        {
            PassMake.GtrPassword aPassMake = new PassMake.GtrPassword(Pass);
            return Json(aPassMake);
        }
    }
}

NecessaryTools/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tools", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"> 
                    <li>@Html.ActionLink("Check", "Index", "MissMatch")</li>
                    <li>@Html.ActionLink("Password Make", "Index", "PassMake")</li>
                    <li>@Html.ActionLink("AL-Yardat", "Index", "AlYardat")</li>
                    <li>@Html.ActionLink("AL-Masrufat", "Index", "AlMasrufat")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tools</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>